### ISSUE TITLE
Missing Comma Operators in RCArmorTokenData.lua

### ISSUE THREAD

**Issue by HealingEmpress** [pelekon/RcLootCouncil-Wotlk#4]
When you added t10 you forgot to add comma defining scope.

Change the file to https://pastebin.com/0aCfsCyN
Otherwise you'll get LUA error.

**Comment by pelekon** [comment]
uuu @query-js I trusted u with that :D 

Anyway fixed

**Comment by query-wow** [comment]
Thanks @HealingEmpress , i forgot, copy pasting issue
